random_seed: 42

paths:
  raw_expression: "data/raw/tcga_brca_expression.tsv.gz"    # genes x samples or samples x genes (we'll detect)
  raw_subtypes:   "data/raw/tcga_brca_pam50_labels.tsv"
  interim_matrix: "data/interim/expression_aligned.parquet"
  processed_train: "data/processed/train.parquet"
  processed_test:  "data/processed/test.parquet"
  figures_dir: "reports/figures"
  models_dir: "models"

preprocess:
  log2_transform: true
  zscore_by_gene: true
  min_nonzero_fraction: 0.05   # drop very-rare genes
  variance_filter_top_k: 5000  # keep top-k variable genes before modeling
  test_size: 0.2

modeling:
  labels: ["Luminal A","Luminal B","HER2-enriched","Basal-like"]
  algorithms:
    - name: "svm_rbf"
      C: [0.5, 1, 2, 5]
      gamma: ["scale","auto"]
    - name: "random_forest"
      n_estimators: [200, 500]
      max_depth: [None, 20, 40]
    - name: "xgboost"
      n_estimators: [400, 800]
      learning_rate: [0.05, 0.1]
      max_depth: [4, 6]
